{{- if .Values.external_dns.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-{{ .Values.serverName }}
  namespace: argocd
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.serverName }}
    namespace: ingress
  source:
    chart: external-dns
    repoURL: {{ .Values.external_dns.repoURL }}
    targetRevision: {{ .Values.external_dns.version }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
