{{- if .Values.ingress_nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-{{ .Values.serverName }}
  namespace: argocd
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.serverName }}
    namespace: ingress
  source:
    chart: ingress-nginx
    repoURL: {{ .Values.ingress_nginx.repoURL }}
    targetRevision: {{ .Values.ingress_nginx.version }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
